In [2]:
import torch
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix

In [16]:
prediction = torch.Tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


target = torch.Tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# per aspect
target = torch.t(target)
prediction = torch.t(prediction)
print('PREDICTION:\n' + str(prediction))
print('\n\nTARGET:\n' + str(target))

PREDICTION:
tensor([[0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
  

In [17]:
print('\t\t Samples')
for i, aspect in enumerate(prediction):
    print(f'Aspect {i} -\t {aspect}')

		 Samples
Aspect 0 -	 tensor([0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.])
Aspect 1 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 2 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 3 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 4 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 5 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 6 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 7 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 8 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 9 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 10 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 11 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 12 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 13 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 14 -	 tensor

In [18]:
# test aspect 16 and and sentiment 2
aspect = 16
sentiment = 2

In [19]:
# masks for visualization
t_mask = prediction[aspect] == sentiment
t_mask

tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=torch.uint8)

In [20]:
# masks for visualization
p_mask = target[aspect] == sentiment
p_mask

tensor([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=torch.uint8)

## This confusion matrix counts the TPs, FPs and FNs for aspect 16 - sentiment 2

In [21]:
confusion_matrix(t_mask, p_mask, labels=[1, 0])

array([[ 1,  0],
       [ 1, 10]])

## Counts all metrics for all aspects and all sentiments

In [22]:
# sentiment + aspect
tp = 0
fp = 0
fn = 0
for a_i in range(20):           # iterate over all aspects
    for s_i in range(1, 4):     # iterate over all sentiment classes (start at 1 to skip n/a labels)
        p_mask = prediction[a_i] == s_i
        t_mask = target[a_i] == s_i
        c_matrix = confusion_matrix(t_mask, p_mask, labels=[1, 0])
        tp += c_matrix[0,0]
        fp += c_matrix[0,1]
        fn += c_matrix[1,0]
        
print(f'TP: {tp}')
print(f'FP: {fp}')
print(f'FN: {fn}')
print(f'Micro F1: {(2 * tp) / (2 * tp + fn + fp)}')

TP: 1
FP: 2
FN: 6
Micro F1: 0.2


In [23]:
# only aspect
tp = 0
fp = 0
fn = 0
for a_i in range(20):
    for s_i in range(1, 4):
        p_mask = prediction[a_i] > 0
        t_mask = target[a_i] > 0
        c_matrix = confusion_matrix(t_mask, p_mask, labels=[1, 0])
        tp += c_matrix[0,0]
        fp += c_matrix[0,1]
        fn += c_matrix[1,0]
        
        
print(f'TP: {tp}')
print(f'FP: {fp}')
print(f'FN: {fn}')
print(f'Micro F1: {(2 * tp) / (2 * tp + fn + fp)}')

TP: 3
FP: 6
FN: 18
Micro F1: 0.2


# Random predictions

In [34]:
prediction = torch.randint(0, 4, (12, 20))
prediction = torch.t(prediction)
prediction

tensor([[1, 0, 2, 2, 3, 2, 2, 3, 3, 0, 1, 1],
        [2, 0, 1, 1, 1, 1, 0, 3, 3, 1, 2, 2],
        [2, 3, 3, 2, 3, 0, 3, 2, 2, 1, 0, 3],
        [1, 3, 1, 1, 0, 2, 2, 1, 3, 0, 0, 0],
        [3, 2, 1, 0, 2, 1, 3, 0, 2, 3, 3, 1],
        [0, 3, 2, 1, 0, 2, 2, 3, 0, 0, 1, 1],
        [0, 1, 1, 2, 0, 3, 0, 2, 2, 0, 1, 1],
        [1, 3, 1, 3, 1, 1, 3, 0, 1, 1, 0, 3],
        [0, 1, 1, 2, 3, 2, 0, 3, 1, 2, 0, 1],
        [0, 2, 1, 2, 1, 1, 3, 3, 1, 1, 1, 2],
        [0, 3, 2, 3, 3, 0, 3, 3, 1, 0, 1, 2],
        [3, 1, 1, 0, 3, 2, 3, 2, 2, 1, 2, 0],
        [3, 3, 3, 0, 1, 0, 3, 0, 1, 0, 2, 2],
        [3, 3, 2, 2, 1, 0, 2, 3, 1, 3, 0, 2],
        [3, 0, 1, 2, 0, 3, 3, 1, 1, 0, 3, 1],
        [3, 0, 1, 2, 2, 1, 2, 2, 2, 0, 3, 1],
        [3, 0, 3, 2, 2, 1, 3, 0, 0, 2, 1, 3],
        [3, 3, 2, 1, 1, 0, 1, 3, 3, 3, 0, 2],
        [0, 0, 3, 3, 2, 3, 2, 1, 0, 3, 3, 1],
        [2, 3, 3, 2, 0, 3, 0, 0, 1, 2, 0, 3]])

In [35]:
# sentiment + aspect
tp = 0
fp = 0
fn = 0
for a_i in range(20):           # iterate over all aspects
    for s_i in range(1, 4):     # iterate over all sentiment classes (start at 1 to skip n/a labels)
        p_mask = prediction[a_i] == s_i
        t_mask = target[a_i] == s_i
        c_matrix = confusion_matrix(t_mask, p_mask, labels=[1, 0])
        tp += c_matrix[0,0]
        fp += c_matrix[0,1]
        fn += c_matrix[1,0]
        
print(f'TP: {tp}')
print(f'FP: {fp}')
print(f'FN: {fn}')
print(f'Micro F1: {(2 * tp) / (2 * tp + fn + fp)}')

TP: 1
FP: 2
FN: 185
Micro F1: 0.010582010582010581


In [38]:
mean_score = 0.0
for i in range(1000):
    prediction = torch.randint(0, 4, (12, 20))
    prediction = torch.t(prediction)
    tp = 0
    fp = 0
    fn = 0
    for a_i in range(20):           # iterate over all aspects
        for s_i in range(1, 4):     # iterate over all sentiment classes (start at 1 to skip n/a labels)
            p_mask = prediction[a_i] == s_i
            t_mask = target[a_i] == s_i
            c_matrix = confusion_matrix(t_mask, p_mask, labels=[1, 0])
            tp += c_matrix[0,0]
            fp += c_matrix[0,1]
            fn += c_matrix[1,0]
    mean_score += (2 * tp) / (2 * tp + fn + fp)
print(f'Mean micro f1: {mean_score/1000}')

Mean micro f1: 0.008330202642978702
