In [2]:
import torch
import torch.nn as nn
import numpy as np
import torch.nn.functional as F
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix


In [4]:
# [batch_size, sentence_lenght, sentiment_classes]
a = torch.ones((12, 42, 3))
a.size()

torch.Size([12, 42, 3])

In [5]:
a = torch.sum(a, dim=1)
a

tensor([[42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.]])

In [ ]:
convLayer = torch.conv1d()

In [2]:
class A(object):
    unique_n: int
    def __init__(self, unique_n):
        print("TEST")
        self.unique_n = unique_n
        
def factory(cls, n):
    print(type(cls))
    return cls(n)

a = factory(A, 1)
b = factory(A, 2)

print(a.unique_n)
print(b.unique_n)
        


<class 'type'>
TEST
<class 'type'>
TEST
1
2


In [4]:
a = torch.ones((12, 20, 4))
a.size()

torch.Size([12, 20, 4])

In [7]:
chunks = torch.chunk(a, 20, dim=1)
chunks[0].size()


torch.Size([12, 1, 4])

In [8]:
b = [torch.ones((12, 20, 4)), torch.ones((12, 20, 4))]
b

[tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1.

In [9]:
torch.sum(b)

TypeError: sum(): argument 'input' (position 1) must be Tensor, not list

In [4]:
prediction = torch.Tensor([[0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])
target = torch.Tensor([[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0]])

In [5]:
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix


In [6]:
prediction.shape

torch.Size([12, 20])

In [7]:
target.shape

torch.Size([12, 20])

In [14]:
i = 2

#prediction.view(20, 12, 1)

target_i = torch.t(target)[i]
target_i[-1] = 1
target_i[-3] = 2
prediction_i = torch.t(prediction)[i]
prediction_i[-1] = 2

print('Target:\t\t' + str(target_i))
print('Prediction:\t' + str(prediction_i))

Target:		tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 1.])
Prediction:	tensor([3., 0., 0., 0., 0., 3., 3., 0., 0., 0., 3., 2.])


### For Label 0
 (TP): 6   (Hits)
 (TN): 1   (When the label is not 0 and the classifier did not predict 0)
 (FP): 1   (When the label is not 0 but the classifier predicted 0)
 (FN): 4   (When the label is 0 but the classifier predicted something else)
     
F1 Score for this label: $\frac{6}{2*6 + 4 + 1}=0,352$


General F1 Score: $\frac{TP}{2*TP + FN + FP}$


### For Label 1:
(TP): 0   (Hits)
other doesn't matter
F1 Score: 0

### For Label 2:
(TP): 0   (Hits)
other doesn't matter
F1 Score: 0

### For Label 3:
no instances: 0
F1 Score: 0

### sklearn f1 score calculation

In [12]:
#print(precision_recall_fscore_support(target_i, prediction_i, beta=1.0, average='binary'))
print(precision_recall_fscore_support(target_i, prediction_i, beta=1.0, average='micro'))
print(precision_recall_fscore_support(target_i, prediction_i, beta=1.0, average='macro'))
print(precision_recall_fscore_support(target_i, prediction_i, beta=1.0, average='samples'))

(0.5, 0.5, 0.5, None)
(0.21428571428571427, 0.15, 0.1764705882352941, None)


/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


ValueError: Sample-based precision, recall, fscore is not meaningful outside multilabel classification. See the accuracy_score instead.

In [16]:
def binary_classification(target, prediction, label):
    mask_target = target == label
    mask_predic = prediction == label
    
    print(mask_target)
    print(mask_predic)
    c_matrix = confusion_matrix(mask_target, mask_predic, labels=[1, 0])
    return c_matrix

def get_metrics(c_matrix):
    tp = c_matrix[0,0]
    fp = c_matrix[0,1]
    fn = c_matrix[1,0]
    tn = c_matrix[1,1]
    return (tp, fp, fn, tn)
c_m = binary_classification(target_i, prediction_i, 0)
print (c_m)
metrics = get_metrics(c_m)
print(metrics)
print(calc_f1(metrics))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0], dtype=torch.uint8)
[[6 4]
 [1 1]]
(6, 4, 1, 1)
0.7058823529411765


In [17]:
i = 2

#prediction.view(20, 12, 1)

target_i = torch.t(target)[i]
prediction_i = torch.t(prediction)[i]

print('Target:\t\t' + str(target_i))
print('Prediction:\t' + str(prediction_i))
print('')

def calc_f1(metrics):
    return (2*metrics[0]) / (2*metrics[0]+metrics[2]+metrics[1])

s_f1 = 0.0
for i in range(4):
    print()
    c_m = binary_classification(target_i, prediction_i, i)
    metrics = get_metrics(c_m)
    f1 = calc_f1(metrics)
    s_f1 += f1
    #print('Own: ' + str(i) + ': ' +str(f1))
    sk_f1 = precision_recall_fscore_support(target_i, prediction_i, beta=1.0, average='micro')
    print('Sklearn: ' + str(i) + ': ' +str(sk_f1))

print('Total: ' + str(s_f1/4))

Target:		tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 1.])
Prediction:	tensor([3., 0., 0., 0., 0., 3., 3., 0., 0., 0., 3., 2.])


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0], dtype=torch.uint8)
Sklearn: 0: (0.5, 0.5, 0.5, None)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=torch.uint8)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)
Sklearn: 1: (0.5, 0.5, 0.5, None)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=torch.uint8)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=torch.uint8)
Sklearn: 2: (0.5, 0.5, 0.5, None)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0], dtype=torch.uint8)
Sklearn: 3: (0.5, 0.5, 0.5, None)
Total: 0.17647058823529413


In [18]:
confusion_matrix(torch.t(target)[i], torch.t(prediction)[i], labels=[0, 3])

array([[5, 3],
       [0, 0]])

In [19]:
# accuracy
print(str(8/12))

0.6666666666666666


In [20]:
tp = 8 # diagonale
fp = 0 + 4 # cols ohne diagonale
fn = 4 + 0 # rows ohne diagonale

f1 = (2* tp)/(2*tp + fn + fp)
f1


0.6666666666666666

In [46]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='micro')

(0.6666666666666666, 0.6666666666666666, 0.6666666666666666, None)

In [50]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='macro')

C:\Users\felix\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


(0.5, 0.3333333333333333, 0.4, None)

In [51]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='weighted')

C:\Users\felix\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


(1.0, 0.6666666666666666, 0.8000000000000002, None)

In [52]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='samples')

ValueError: Sample-based precision, recall, fscore is not meaningful outside multilabel classification. See the accuracy_score instead.

In [65]:
a = [1, 2]
np.mean(a)

1.5

In [7]:
from models.softmax_output import ConvSoftmaxOutputLayerWithCommentWiseClass
num_filters = 8
kernel_size = 5
model_size = 30
stride = 1
padding = 0
sentence_lenght = 10
h_in = 10
w_in = model_size
x = torch.ones((12, h_in, w_in))
x.shape

torch.Size([12, 10, 30])

In [8]:

conv = nn.Sequential(
			nn.Conv2d(1, num_filters, (kernel_size, model_size), stride, padding),
			nn.ReLU()
		)
conv_out = ((h_in + 2 * padding - 1 * (kernel_size - 1) - 1) // 1) + 1

pooling = nn.MaxPool2d((conv_out, 1), stride=stride)
output_projection = nn.Linear(num_filters, 4)
conv_out

6

In [9]:
x = x.unsqueeze(1)
x.shape

torch.Size([12, 1, 10, 30])

In [12]:
x[0][0]

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.

In [13]:
x_conv = conv(x)
x_conv.shape

torch.Size([12, 8, 6, 1])

In [18]:
x_conv[1]

tensor([[[0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[0.3021],
         [0.3021],
         [0.3021],
         [0.3021],
         [0.3021],
         [0.3021]],

        [[0.2384],
         [0.2384],
         [0.2384],
         [0.2384],
         [0.2384],
         [0.2384]],

        [[0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[0.6698],
         [0.6698],
         [0.6698],
         [0.6698],
         [0.6698],
         [0.6698]],

        [[0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[0.3373],
         [0.3373],
         [0.3373],
         [0.3373],
         [0.3373],
         [0.3373]],

        [[0.4115],
         [0.4115],
         [0.4115],
         [0.4115],
         [0.4115],
         [0.4115]]], grad_fn=<SelectBackward>)

In [16]:
x_pad = pooling(x_conv)
x_pad = x_pad.squeeze().squeeze()
x_pad.shape

torch.Size([12, 8])

In [17]:
x_pad[0]

tensor([0.0000, 0.3021, 0.2384, 0.0000, 0.6698, 0.0000, 0.3373, 0.4115],
       grad_fn=<SelectBackward>)

In [25]:
x_out = output_projection(x_pad)
x_out.shape

torch.Size([12, 4])

In [26]:
x_out

tensor([[-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481]], grad_fn=<AddmmBackward>)

In [29]:
softmax = F.log_softmax(x_out, dim=-1)
softmax

tensor([[-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007]], grad_fn=<LogSoftmaxBackward>)

In [30]:
softmax = F.softmax(x_out, dim=-1)
softmax

tensor([[0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017]], grad_fn=<SoftmaxBackward>)

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F

output = Variable(torch.FloatTensor([0,0,0,1])).view(1, -1)
target = Variable(torch.LongTensor([3]))

print(output)
output = F.log_softmax(output)
print(output)


criterion = nn.NLLLoss()
loss = criterion(output, target)
print(loss)

tensor([[0., 0., 0., 1.]])
tensor([[-1.7437, -1.7437, -1.7437, -0.7437]])
tensor(0.7437)


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.


### Test perfect prediction

In [24]:
target_i = torch.t(target)[i]
target_i[-1] = 1
target_i[-3] = 2
target_i[0] = 3
target_i[5] = 3
target_i[7] = 1
target_i[8] = 1
target_i[-3] = 3
target_i[-2] = 2

prediction_i = torch.t(prediction)[i]
prediction_i[-1] = 1
prediction_i[-2] = 3

print('Target:\t\t' + str(target_i))
print('Prediction:\t' + str(prediction_i))

Target:		tensor([3., 0., 0., 0., 0., 3., 0., 1., 1., 3., 2., 1.])
Prediction:	tensor([3., 0., 0., 0., 0., 3., 0., 1., 1., 3., 3., 1.])


In [25]:
s_f1 = 0.0
for i in range(4):
    print()
    c_m = binary_classification(target_i, prediction_i, i)
    metrics = get_metrics(c_m)
    f1 = calc_f1(metrics)
    s_f1 += f1
    #print('Own: ' + str(i) + ': ' +str(f1))
    sk_f1 = precision_recall_fscore_support(target_i, prediction_i, beta=1.0, average='micro')
    print('Sklearn: ' + str(i) + ': ' +str(sk_f1))

print('Total: ' + str(s_f1/4))


tensor([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0], dtype=torch.uint8)
Sklearn: 0: (0.9166666666666666, 0.9166666666666666, 0.9166666666666666, None)

tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1], dtype=torch.uint8)
tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1], dtype=torch.uint8)
Sklearn: 1: (0.9166666666666666, 0.9166666666666666, 0.9166666666666666, None)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)
Sklearn: 2: (0.9166666666666666, 0.9166666666666666, 0.9166666666666666, None)

tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0], dtype=torch.uint8)
tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0], dtype=torch.uint8)
Sklearn: 3: (0.9166666666666666, 0.9166666666666666, 0.9166666666666666, None)
Total: 0.7142857142857143


In [12]:
prediction = torch.Tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


target = torch.Tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# per aspect
target = torch.t(target)
prediction = torch.t(prediction)
print('PREDICTION:\n' + str(prediction))
print('\n\nTARGET:\n' + str(target))

PREDICTION:
tensor([[0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
  

In [14]:
print('\t\t Samples')
for i, aspect in enumerate(prediction):
    print(f'Aspect {i} -\t {aspect}')

		 Samples
Aspect 0 -	 tensor([0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.])
Aspect 1 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 2 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 3 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 4 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 5 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 6 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 7 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 8 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 9 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 10 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 11 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 12 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 13 -	 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Aspect 14 -	 tensor

In [45]:
aspect = 16
sentiment = 2

t_mask = prediction[aspect] == sentiment
t_mask

tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=torch.uint8)

In [46]:
p_mask = target[aspect] == sentiment
p_mask

tensor([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=torch.uint8)

In [43]:
confusion_matrix(t_mask, p_mask, labels=[1, 0])

array([[ 1,  0],
       [ 1, 10]])

In [44]:
# sentiment + aspect
tp = 0
fp = 0
fn = 0
for a_i in range(20):
    for s_i in range(1, 4):
        p_mask = prediction[a_i] == s_i
        t_mask = target[a_i] == s_i
        c_matrix = confusion_matrix(t_mask, p_mask, labels=[1, 0])
        tp += c_matrix[0,0]
        fp += c_matrix[0,1]
        fn += c_matrix[1,0]
        
print(tp)
print(fp)
print(fn)

1
2
6


In [48]:
# only aspect
tp = 0
fp = 0
fn = 0
for a_i in range(20):
    p_mask = prediction[a_i] > 0
    t_mask = target[a_i] > 0
    c_matrix = confusion_matrix(t_mask, p_mask, labels=[1, 0])
    tp += c_matrix[0,0]
    fp += c_matrix[0,1]
    fn += c_matrix[1,0]
        
        
print(tp)
print(fp)
print(fn)

1
2
6


In [42]:
p_mask

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)

In [43]:
t_mask

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)

In [44]:
t_mask.size()

torch.Size([12])

In [45]:
c_matrix = confusion_matrix(t_mask, p_mask, labels=[1, 0])
c_matrix

array([[ 0,  0],
       [ 0, 12]])