In [1]:
import torch
import torch.nn as nn
import numpy as np
import torch.nn.functional as F


In [4]:
# [batch_size, sentence_lenght, sentiment_classes]
a = torch.ones((12, 42, 3))
a.size()

torch.Size([12, 42, 3])

In [5]:
a = torch.sum(a, dim=1)
a

tensor([[42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.]])

In [ ]:
convLayer = torch.conv1d()

In [2]:
class A(object):
    unique_n: int
    def __init__(self, unique_n):
        print("TEST")
        self.unique_n = unique_n
        
def factory(cls, n):
    print(type(cls))
    return cls(n)

a = factory(A, 1)
b = factory(A, 2)

print(a.unique_n)
print(b.unique_n)
        


<class 'type'>
TEST
<class 'type'>
TEST
1
2


In [4]:
a = torch.ones((12, 20, 4))
a.size()

torch.Size([12, 20, 4])

In [7]:
chunks = torch.chunk(a, 20, dim=1)
chunks[0].size()


torch.Size([12, 1, 4])

In [8]:
b = [torch.ones((12, 20, 4)), torch.ones((12, 20, 4))]
b

[tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1.

In [9]:
torch.sum(b)

TypeError: sum(): argument 'input' (position 1) must be Tensor, not list

In [3]:
prediction = torch.Tensor([[0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])
target = torch.Tensor([[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0]])

In [4]:
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix


In [17]:
prediction.shape


torch.Size([12, 20])

In [18]:
target.shape

torch.Size([12, 20])

In [43]:
i = 2

#prediction.view(20, 12, 1)

target_i = torch.t(target)[i]
target_i[-1] = 1
target_i[-3] = 2
prediction_i = torch.t(prediction)[i]
prediction_i[-1] = 2

print('Target:\t\t' + str(target_i))
print('Prediction:\t' + str(prediction_i))

Target:		tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 1.])
Prediction:	tensor([3., 0., 0., 0., 0., 3., 3., 0., 0., 0., 3., 2.])


In [44]:
def binary_classification(target, prediction, label):
    mask_target = target == label
    mask_predic = prediction == label
    
    print(mask_target)
    print(mask_predic)
    c_matrix = confusion_matrix(mask_target, mask_predic, labels=[1, 0])
    return c_matrix

def get_metrics(c_matrix):
    tp = c_matrix[0,0]
    fp = c_matrix[0,1]
    fn = c_matrix[1,0]
    tn = c_matrix[1,1]
    return (tp, fp, fn, tn)
c_m = binary_classification(target_i, prediction_i, 0)
print (c_m)
metrics = get_metrics(c_m)
print(metrics)
print(calc_f1(metrics))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0], dtype=torch.uint8)
[[6 4]
 [1 1]]
(6, 4, 1, 1)
0.7058823529411765


In [46]:
i = 2

#prediction.view(20, 12, 1)

target_i = torch.t(target)[i]
prediction_i = torch.t(prediction)[i]

print('Target:\t\t' + str(target_i))
print('Prediction:\t' + str(prediction_i))


def calc_f1(metrics):
    return (2*metrics[0]) / (2*metrics[0]+metrics[2]+metrics[1])

s_f1 = 0.0
for i in range(4):
    c_m = binary_classification(target_i, prediction_i, i)
    metrics = get_metrics(c_m)
    f1 = calc_f1(metrics)
    s_f1 += f1
    print(str(i) + ': ' +str(f1))
    
print('Total: ' + str(s_f1/4))

Target:		tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 1.])
Prediction:	tensor([3., 0., 0., 0., 0., 3., 3., 0., 0., 0., 3., 2.])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0], dtype=torch.uint8)
0: 0.7058823529411765
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=torch.uint8)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)
1: 0.0
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=torch.uint8)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=torch.uint8)
2: 0.0
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0], dtype=torch.uint8)
3: 0.0
Total: 0.17647058823529413


In [63]:
confusion_matrix(torch.t(target)[i], torch.t(prediction)[i], labels=[0, 3])

array([[0, 0],
       [0, 0]], dtype=int64)

In [59]:
# accuracy
print(str(8/12))

0.6666666666666666


In [60]:
tp = 8 # diagonale
fp = 0 + 4 # cols ohne diagonale
fn = 4 + 0 # rows ohne diagonale

f1 = (2* tp)/(2*tp + fn + fp)
f1


0.6666666666666666

In [46]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='micro')

(0.6666666666666666, 0.6666666666666666, 0.6666666666666666, None)

In [50]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='macro')

C:\Users\felix\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


(0.5, 0.3333333333333333, 0.4, None)

In [51]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='weighted')

C:\Users\felix\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


(1.0, 0.6666666666666666, 0.8000000000000002, None)

In [52]:
precision_recall_fscore_support(torch.t(target)[i], torch.t(prediction)[i], beta=1.0, average='samples')

ValueError: Sample-based precision, recall, fscore is not meaningful outside multilabel classification. See the accuracy_score instead.

In [65]:
a = [1, 2]
np.mean(a)

1.5

In [7]:
from models.softmax_output import ConvSoftmaxOutputLayerWithCommentWiseClass
num_filters = 8
kernel_size = 5
model_size = 30
stride = 1
padding = 0
sentence_lenght = 10
h_in = 10
w_in = model_size
x = torch.ones((12, h_in, w_in))
x.shape

torch.Size([12, 10, 30])

In [8]:

conv = nn.Sequential(
			nn.Conv2d(1, num_filters, (kernel_size, model_size), stride, padding),
			nn.ReLU()
		)
conv_out = ((h_in + 2 * padding - 1 * (kernel_size - 1) - 1) // 1) + 1

pooling = nn.MaxPool2d((conv_out, 1), stride=stride)
output_projection = nn.Linear(num_filters, 4)
conv_out

6

In [9]:
x = x.unsqueeze(1)
x.shape

torch.Size([12, 1, 10, 30])

In [12]:
x[0][0]

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.

In [13]:
x_conv = conv(x)
x_conv.shape

torch.Size([12, 8, 6, 1])

In [18]:
x_conv[1]

tensor([[[0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[0.3021],
         [0.3021],
         [0.3021],
         [0.3021],
         [0.3021],
         [0.3021]],

        [[0.2384],
         [0.2384],
         [0.2384],
         [0.2384],
         [0.2384],
         [0.2384]],

        [[0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[0.6698],
         [0.6698],
         [0.6698],
         [0.6698],
         [0.6698],
         [0.6698]],

        [[0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[0.3373],
         [0.3373],
         [0.3373],
         [0.3373],
         [0.3373],
         [0.3373]],

        [[0.4115],
         [0.4115],
         [0.4115],
         [0.4115],
         [0.4115],
         [0.4115]]], grad_fn=<SelectBackward>)

In [16]:
x_pad = pooling(x_conv)
x_pad = x_pad.squeeze().squeeze()
x_pad.shape

torch.Size([12, 8])

In [17]:
x_pad[0]

tensor([0.0000, 0.3021, 0.2384, 0.0000, 0.6698, 0.0000, 0.3373, 0.4115],
       grad_fn=<SelectBackward>)

In [25]:
x_out = output_projection(x_pad)
x_out.shape

torch.Size([12, 4])

In [26]:
x_out

tensor([[-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481],
        [-0.0789,  0.1683, -0.0202, -0.2481]], grad_fn=<AddmmBackward>)

In [29]:
softmax = F.log_softmax(x_out, dim=-1)
softmax

tensor([[-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007],
        [-1.4316, -1.1844, -1.3729, -1.6007]], grad_fn=<LogSoftmaxBackward>)

In [30]:
softmax = F.softmax(x_out, dim=-1)
softmax

tensor([[0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017],
        [0.2389, 0.3059, 0.2534, 0.2017]], grad_fn=<SoftmaxBackward>)